name: Deploy Model

on:
  workflow_dispatch:
    inputs:
      model_name:
        description: "Name of the model"
        required: true
      model_version:
        description: "Version of the model"
        required: true
      deploy_target:
        description: "Where to deploy (e.g. AWS, GCP)"
        required: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Show config
        run: |
          echo "Model: ${{ github.event.inputs.model_name }}"
          echo "Version: ${{ github.event.inputs.model_version }}"
          echo "Deploying to: ${{ github.event.inputs.deploy_target }}"

      - name: Mock Docker build
        run: |
          echo "Pretending to build image for model: ${{ github.event.inputs.model_name }}"
          echo "Version: ${{ github.event.inputs.model_version }}"
          # need to add actual docker build commands


      - name: Deploy to target
        run: |
          echo "Deploying to ${{ github.event.inputs.deploy_target }}..."
          # need to add AWS CLI, GCP CLI, or kubectl commands 

